name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish ./dot-net-api/dot-net-api.csproj -c Release -o ${{env.DOTNET_ROOT}}/api

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: api-artifact
          path: ${{env.DOTNET_ROOT}}/api

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: api-artifact

      - name: Deploy to Azure Web App
        id: deploy-to-azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'climbing-gym-dev'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: api-artifact

      - name: Deploy to Azure Web App
        id: deploy-to-azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'climbing-gym-prod'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}

